[package]
name = "b-top"
version = "0.1.3"
edition = "2024"

[dependencies]
prompted = "0.2.8"

ratatui = "0.29"
crossterm = "0.29"
tachyonfx = "0.15"
sysinfo = "0.36"

textplots = "0.8"

libc = "0.2"

lazy_static = "1.4"
